# Generated by Django 4.0.5 on 2024-11-19 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(choices=[('Fiat', 'Fiat'), ('Chevrolet', 'Chevrolet'), ('Ford', 'Ford'), ('Toyota', 'Toyota'), ('Honda', 'Honda'), ('Volkswagen', 'Volkswagen'), ('Nissan', 'Nissan'), ('Hyundai', 'Hyundai')], max_length=20, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('serial_carroceria', models.CharField(max_length=50, unique=True, verbose_name='Serial de Carrocería')),
                ('serial_motor', models.CharField(max_length=50, unique=True, verbose_name='Serial del Motor')),
                ('categoria', models.CharField(choices=[('Particular', 'Particular'), ('Transporte', 'Transporte'), ('Carga', 'Carga'), ('Comercial', 'Comercial')], max_length=20, verbose_name='Categoría')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('año', models.IntegerField(help_text='Año del vehículo', verbose_name='Año')),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
